networks:
  traefik:
    name: ${DOCKER_NETWORK_NAME}

services:
  bbs-go:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: ..
      dockerfile: build/Dockerfile
      args: 
        APP_NAME: ${APP_NAME}
        LISTEN_ADDR: ${LISTEN_ADDR} 
        LISTEN_PORT: ${LISTEN_PORT} 
        GOLANG_VERSION: ${GOLANG_VERSION}
        TZ: ${TZ}
    restart: unless-stopped
    environment:
      PROJECT_VERSION: ${PROJECT_VERSION}
      SWAPI_TOKEN: ${SWAPI_TOKEN}
    cpus: 0.2
    dns:
      - 10.4.5.130
      - 1.0.0.2
    mem_reservation: 128m
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}"
    networks:
      - traefik

