version: '3.6'

networks:
  traefik_savla:
    name: ${DOCKER_NETWORK_NAME}

services:
  swapp:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: .
      args: 
        APP_NAME: ${APP_NAME}
        LISTEN_ADDR: ${LISTEN_ADDR} 
        LISTEN_PORT: ${LISTEN_PORT} 
        GOLANG_VERSION: ${GOLANG_VERSION}
        TZ: ${TZ}
    restart: unless-stopped
    cpus: 0.5
    dns:
      - 1.1.1.2
      - 10.4.5.130
      - 1.0.0.2
    mem_reservation: 512m
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"

